BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            size_hint_x: 5
            id: miles
            text: '0'
        BoxLayout:
            orientation: 'vertical'
            Button:
                on_press: app.handle_up()
                text: 'Up'
            Button:
                on_press: app.handle_down()
                text: 'Down'
    Button:
        on_press: app.handle_convert()
        text: 'Convert miles to km'
    Label:
        id: km
        text: '0'